# Generated by Django 2.2 on 2019-05-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190512_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_name', to='catalog.Tovar', verbose_name='Товар'),
        ),
    ]
