# Generated by Django 2.0.13 on 2019-05-24 17:07

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0005_profile_logo'),
        ('product', '0005_auto_20190513_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=product.models.get_upload_path, verbose_name='Фото компании')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixuser.Profile', verbose_name='Автор')),
            ],
        ),
    ]
