# Generated by Django 2.0.13 on 2019-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_banner_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннера'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='status',
            field=models.IntegerField(choices=[(1, 'Бесплатный'), (2, 'Базовый'), (3, 'Расширенный')], default='1'),
        ),
    ]
