# Generated by Django 2.0.13 on 2019-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190527_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='status',
            field=models.IntegerField(choices=[(1, 'Бесплатный'), (2, 'Базовый'), (3, 'Расширенный')], default=1),
        ),
    ]
