# Generated by Django 2.0.13 on 2019-05-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190527_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='felixuser.Profile'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='felixuser.Profile'),
        ),
    ]
