# Generated by Django 2.0.13 on 2019-05-29 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.ManyToManyField(blank=True, null=True, related_name='zones', to=settings.AUTH_USER_MODEL),
        ),
    ]
