# Generated by Django 2.0.13 on 2019-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190603_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/banner/{user.id}', verbose_name='Акция'),
        ),
    ]
