# Generated by Django 2.0.13 on 2019-06-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190603_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='fon',
            field=models.IntegerField(choices=[(1, 'Светлый'), (2, 'Темный')], default=1),
        ),
    ]
