# Generated by Django 2.0.13 on 2019-06-03 15:57

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_banner_fon'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.CharField(default='', max_length=150, verbose_name='Текст на баннере'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='fon',
            field=models.IntegerField(choices=[(1, 'Светлый'), (2, 'Темный')], default=1, verbose_name='Фон оформления'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='static/banner/{user}/', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=product.models.get_upload_path, verbose_name='Фото компании'),
        ),
    ]
