# Generated by Django 2.2 on 2019-05-15 00:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.BigIntegerField(default='0', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='count',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер менеджера')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('city', models.CharField(default='Одесса', max_length=200, verbose_name='Город')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('weight', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Объем')),
                ('is_all', models.BooleanField(default=False, verbose_name='Отправить для всех получателей')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tovar', verbose_name='Товар')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Производитель')),
            ],
        ),
    ]
