# Generated by Django 2.2 on 2019-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190516_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCheck',
        ),
    ]
