# Generated by Django 2.2 on 2019-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_ordercheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
        migrations.AddField(
            model_name='order',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
    ]
