# Generated by Django 2.0.13 on 2019-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190516_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='weight',
            field=models.CharField(choices=[('м<sup><small>3</small></sup>', 'Кубометр'), ('шт.', 'Штук'), ('т.', 'Тонна')], default='шт.', max_length=250),
        ),
    ]
