# Generated by Django 2.2 on 2019-05-08 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=500, verbose_name='Название компании')),
                ('identificate', models.CharField(max_length=10, verbose_name='ИНН')),
                ('director', models.TextField(default='', max_length=500, verbose_name='Директор')),
                ('city', models.CharField(default='odessa', max_length=200, verbose_name='Город')),
                ('site', models.URLField(blank=True, default='', verbose_name='Адрес сайта')),
                ('manager', models.TextField(default='', max_length=200, verbose_name='Имя менеджера')),
                ('image', models.ImageField(blank=True, upload_to='static/avatars', verbose_name='Фото менеджера')),
                ('admin', models.CharField(default='', max_length=200, verbose_name='Имя администратора')),
                ('specialisation', models.ManyToManyField(to='catalog.Category', verbose_name='Основной вид дейтельности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
