# Generated by Django 2.2 on 2019-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Улица', max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Одесса', max_length=200, verbose_name='Город'),
        ),
    ]
