# Generated by Django 2.2 on 2019-05-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0002_auto_20190508_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер менеджера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Улица', max_length=200, verbose_name='Улица'),
        ),
    ]
