# Generated by Django 2.2 on 2019-05-11 03:59

from django.db import migrations, models
import felixuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190508_1823'),
        ('felixuser', '0003_auto_20190511_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='regions',
            field=models.ManyToManyField(to='catalog.City', verbose_name='Регионы доставки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес склада'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=felixuser.models.get_upload_path, verbose_name='Фото менеджера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.URLField(blank=True, verbose_name='Адрес сайта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='Улица', max_length=200, verbose_name='Адрес офиса'),
        ),
    ]
