# Generated by Django 2.0.13 on 2019-05-25 18:32

from django.db import migrations, models
import felixuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0008_auto_20190525_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=felixuser.models.get_upload_path, verbose_name='Лого компании'),
        ),
    ]
