# Generated by Django 2.0.13 on 2019-05-27 15:05

from django.db import migrations, models
import felixuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0009_auto_20190525_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, upload_to=felixuser.models.get_upload_path2, verbose_name='Лого компании'),
        ),
    ]
