# Generated by Django 2.0.13 on 2019-05-27 17:49

from django.db import migrations
import django_resized.forms
import felixuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0010_auto_20190527_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[150, 150], upload_to=felixuser.models.get_upload_path, verbose_name='Фото менеджера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[150, 150], upload_to=felixuser.models.get_upload_path2, verbose_name='Лого компании'),
        ),
    ]
