# Generated by Django 2.0.13 on 2019-06-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixuser', '0013_smsverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverify',
            name='number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Номер менеджера'),
        ),
    ]
